name: Ping URL every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the target URL
        run: curl -s -o /dev/null -w "%{http_code}" https://course-generator-backend-0-1-0.onrender.com/docs